#pragma once
#include <ucurses/component/Menu.hpp>
#include <ucurses/component/FileMenu.hpp>
#include <ucurses/component/TextEntry.hpp>
#include <ucurses/component/Label.hpp>
#include <ucurses/component/Canvas.hpp>
#include <ucurses/component/Slider.hpp>
#include <ucurses/component/SliderMenu.hpp>
#include <ucurses/component/ScrollableMenu.hpp>
